-- Migration para criar a tabela de leituras
CREATE TABLE public.leituras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    temperatura NUMERIC NOT NULL,
    presenca BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Configurando políticas de segurança (RLS)
ALTER TABLE public.leituras ENABLE ROW LEVEL SECURITY;

-- Permitir inserção para usuários autenticados
CREATE POLICY "Permitir inserção de leituras para usuários autenticados" 
ON public.leituras FOR INSERT 
TO authenticated 
WITH CHECK (true);

-- Permitir leitura para usuários autenticados
CREATE POLICY "Permitir leitura de leituras para usuários autenticados" 
ON public.leituras FOR SELECT 
TO authenticated 
USING (true);
